name: Build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.16+
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: make build

    - name: Notify Slack
      uses: rtCamp/action-slack-notify@v2
      if: ${{ github.event_name == 'push' && success() }}
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: ops
        SLACK_USERNAME: ${{ github.repository }}
        SLACK_MESSAGE: "CLI :terminal: build success :success:"

    - name: Notify Slack on failure
      uses: rtCamp/action-slack-notify@v2
      if: ${{ ! success() }}
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: ops
        SLACK_USERNAME: ${{ github.repository }}
        SLACK_MESSAGE: "CLI :terminal: build *FAILED* :fire:"