name: public repo release

on:
  release:
    types: [published]

jobs:
  publish-release:
    runs-on: macOS-latest
    steps:
    - name: Checks if pre-release
      if: github.event.release.prerelease == true
      run: |
        echo This is running against a pre-release.
        echo Skipping all the next steps.

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get tag name
      id: get_tag_name
      run: echo ::set-output name=VERSION::$(cat version.txt)

    - name: Use gh to release to cli-release repo
      if: github.event.release.prerelease != true
      env:
        RELEASE_TAG: ${{ steps.get_tag_name.outputs.VERSION }}
        GITHUB_USER: ${{ secrets.GH_USER }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        gh --version
        gh -R aardlabs/terminal-poc release download ${RELEASE_TAG}
        echo "Release: ${RELEASE_TAG}" > changelog.md
        gh -R aardlabs/cli-release release create ${RELEASE_TAG} aard*.zip -F changelog.md