on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - 'version.txt'

name: Release

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
        - name: Set up Go 1.16+
          uses: actions/setup-go@v2
          with:
            go-version: ^1.16
          id: go

        - name: Check out code into the Go module directory
          uses: actions/checkout@v2

        - name: Get tag name
          id: get_tag_name
          run: echo ::set-output name=VERSION::$(cat version.txt)

        - name: Build x64 linux release
          run: make release/linux

        - name: Zip linux build
          run: zip -j aard-linux-amd64.zip README.md bin/linux/*

        - name: Build x64 darwin release
          run: make release/darwin

        - name: Zip darwin build
          run: zip -j aard-darwin-amd64.zip README.md bin/darwin/*

        - name: Create Release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_USER: ${{ secrets.GH_USER }}
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          with:
            tag_name: ${{ steps.get_tag_name.outputs.VERSION }}
            release_name: Release ${{ steps.get_tag_name.outputs.VERSION }}
            draft: false
            prerelease: false

        - name: Upload Linux Release Binary
          id: upload-release-binary-linux
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_USER: ${{ secrets.GH_USER }}
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ./bin/linux/aard
            asset_name: aard-linux-amd64
            asset_content_type: application/octet-stream

        - name: Upload Linux Release Asset
          id: upload-release-asset-linux
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_USER: ${{ secrets.GH_USER }}
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ./aard-linux-amd64.zip
            asset_name: aard-linux-amd64-${{ steps.get_tag_name.outputs.VERSION }}.zip
            asset_content_type: application/zip

        - name: Upload darwin Release Asset
          id: upload-release-asset-darwin
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_USER: ${{ secrets.GH_USER }}
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ./aard-darwin-amd64.zip
            asset_name: aard-darwin-amd64-${{ steps.get_tag_name.outputs.VERSION }}.zip
            asset_content_type: application/zip
